spring.application.name=IFCD0014_2026_02_BIBLIOVIDEO
# Puerto del servidor (opcional)
server.port=8080
# Configuraci�n de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/movies-db
spring.datasource.username=usr-app-movies
spring.datasource.password=usr-app-movies
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuraci�n JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Log del Hikari (Pool de conexiones)
# Con este atributo en modo DEBUG da informaci�n del POOL
logging.level.com.zaxxer.hikari=DEBUG
# Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

